### ISSUE TITLE
extracting latent dimensions from CCA fit + GridsearchCV import error

### ISSUE THREAD

**Issue by LegrandNico** [jameschapman19/cca_zoo#123]
Hi,

Thank you for this amazing toolbox, I think that is something that was really missing in the Python ecosystem :raised_hands:

I would like to apply different flavours of CCA to resting-state fMRI connectivity and behavioural data, and would like to be able to reproduce the analyses described in this paper:

> Wang HT, Poerio G, Murphy C, Bzdok D, Jefferies E, Smallwood J. Dimensions of Experience: Exploring the Heterogeneity of the Wandering Mind. Psychol Sci. 2018 Jan;29(1):56-71. doi: 10.1177/0956797617728727. Epub 2017 Nov 13. PMID: 29131720; PMCID: PMC6346304.

However, I am not sure exactly how the API let you extract the different views of the CCA fit (i.e. the different orthogonal dimensions). I tried to change the `latent_dims` parameters but the size of the CCA weights is still the same (should we get different weights from each view?). Sorry if this is a very simple question, I am just starting with CCA.

Then I tried to fit_transform the data using [a code example from the user manual](https://cca-zoo.readthedocs.io/en/latest/documentation/user_guide.html) to apply recursively many CCA, but get this error:

```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_1377153/194783063.py in <module>
      1 from cca_zoo.models import rCCA
----> 2 from cca_zoo.model_selection import GridsearchCV
      3 
      4 def scorer(estimator,X):
      5     dim_corrs=estimator.score(X)

ImportError: cannot import name 'GridsearchCV' from 'cca_zoo.model_selection' (/opt/anaconda3/lib/python3.8/site-packages/cca_zoo/model_selection/__init__.py)
```

I am happy to help writing documentation, plotting functionalities or testing things if that can help.

**Comment by jameschapman19** [comment]
Firstly thanks for the spot on the import error. I have just pushed a new version that fixes it (I think).

On extracting the scores/latent_dimensions if you call model.transform((view 1, view 2)) then that gives you the scores/latent_dimensions for each view. If you call model.get_loadings((view 1, view 2)) then that should give the loadings for each view.

Your use case is somewhat aligned with my original goal writing this package (I started off translating some MATLAB code for doing analysis of neuroimaging and behaviour data) so I'm absolutely open to contributions in any form (verbal feedback/PRs)

**Comment by jameschapman19** [comment]
weights attribute will be a list as long as the number of views in your input i.e. each element of weights are the weights for each view. So the thing that will change is the size of the elements of weights if you see what I mean.

**Comment by LegrandNico** [comment]
Thank you for the clarification, I think I was just unsure about the difference between weights and loadings.

I will propose other contributions in separate issues so we can close this one as the import error has been fixed.

**Comment by vignesh294** [comment]
Hi, I am still getting the ImportError: cannot import name 'GridsearchCV' from 'cca_zoo.model_selection' (/opt/anaconda3/lib/python3.8/site-packages/cca_zoo/model_selection/__init__.py). Any idea? Using the latest version.
